Bulk samples submission service return validation errors
EBIBioSamples/biosamples-v4 pull request #714
Opened 2024-07-01 15:09 UTC by theisuru

ebi-ait/checklist#45

- Add validation for all users including superuser (Will there be any problems with exporting or any other logic? discuss)
- Validate all before attempting to persist
- If validation fails, do not submit anything
  -  There could be other validation steps that fails when trying to persist. This can still cause partially persisted data

2024-07-01 15:53 UTC, amnonkhen commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +  private static String getWebinSubmissionAccount(boolean isWebinSubmission, Optional<AuthToken> authToken) {
Nice cleanup. I think boolean parameters are a bit confusing. I am sure there is a cleaner option here.

2024-07-01 15:53 UTC, amnonkhen commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +  private void validateSample(Sample sample, final boolean isWebinSubmission) {
`isWebinSubmission` is not used in the body of the function.

2024-07-01 15:53 UTC, amnonkhen commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +    if (isWebinSubmission) {
This `if(isWebinSubmission)` is repeating in several cases. I would suggest to have 2 implementation classes, one for webin, another for not-webin, and a factory method at the beginning.

2024-07-01 15:53 UTC, amnonkhen commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +    // suggestion: First do all validation and persist only if validation is successful
Should each document in the bulk be validated and submitted separately? I.e. If there are 2 documents, one of which is invalid, should just the valid one be persisted, or should both be rejected?

2024-07-01 15:53 UTC, amnonkhen commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +    boolean isWebinSubmission = authProvider == AuthorizationProvider.WEBIN;
Instead of passing isWebinSubmission to all functions and having an `if` in each function, it would be cleaner to have 2 implementation classes of the submission logic, and a factory method to select it.

2024-07-04 09:22 UTC, dipayan1985 requested changes
Changes requested for

- Keeping the current behaviour of persisting valid and rejecting invalid samples in a batch
- Enabling whether to validate or not validate all samples via a flag (this is optional and only to be done if this code is merged to dev. If you are willing to deploy the branch to dev this change might not be required.
- Requesting BioSamples changes to be tracked via a ticket with sub-tasks in BioSamples Kanban.

2024-07-04 09:22 UTC, dipayan1985 commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +    // suggestion: First do all validation and persist only if validation is successful
In the current model, we don't validate samples in BioSamples that are routed from Webin and all samples are persisted. Webin checks at its end if it has sent X samples to BioSamples and received X samples accessioned from BioSamples. If it is X-1 Webin submission fails. 

Preferably continue this model, in a batch if validation fails for some samples reject them, and if validation passes persist them.

Bulk submission is currently only used by Webin but it is intended for any other archives who want to integrate with BioSamples. Other archives might handle it differently from Webin and retry for only failed samples.

Webin-routed samples are initially submitted private to BioSamples and there is a separate process to make them public when ENA data becomes public. hence if from a Webin submission of 100 samples, 50 are validated and persisted and 50 are invalid and not persisted, we end up having 50 stale private samples in the system but we don't mind that.

2024-07-04 09:22 UTC, dipayan1985 commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +    validateAllSamples(samples, isWebinSubmission);
For me the only change would be in `persistSampleV2WebinAuth`

`if (!isWebinSuperUser) {
      sample = validateSample(sample, true);
    }`
to 
`sample = validateSample(sample, true);`

Preferably add a property in the application.properties that enables turning this off and on, because if we merge this to dev and then during a release if we merge dev -> master, we will accidentally deliver this change to prod without testing and performance statistics. 

Please keep the property true (validate all samples) in dev and false (not validate all samples) in production.

2024-07-05 09:29 UTC, amnonkhen commented on webapps/core-v2/src/main/java/uk/ac/ebi/biosamples/controller/BulkActionControllerV2.java
> +    // suggestion: First do all validation and persist only if validation is successful
@dipayan1985 In your 100 samples example, which 50 is stale?

2024-07-08 09:14 UTC, theisuru commented
Hi both, 
I reverted back changes and only introduced following two changes
- Add flag in `BioSamplesProperties` to enable/disable webinSuperuserValidation
- Validate webin superuser only if flag is `true`. Default value for the flag is `false`. 

(linking ebi-ait/checklist#45)

2024-07-12 10:16 UTC, amnonkhen approved these changes

2024-07-17 08:42 UTC, merged